# Generated by Django 3.0.7 on 2020-06-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wihda',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('school_year', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.School')),
            ],
        ),
    ]
