# Generated by Django 3.0.7 on 2020-07-05 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200619_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wihda',
            options={'verbose_name_plural': 'Wihdat'},
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('wihda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wihda')),
            ],
        ),
    ]
