# Generated by Django 3.0.7 on 2020-07-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200705_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercice',
                     'verbose_name_plural': 'Exercices'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='التمرين __', max_length=150),
        )
    ]
