# Generated by Django 3.0.7 on 2020-07-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200708_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='wihda',
            name='summary',
            field=models.URLField(blank=True, null=True),
        )
    ]
