# Generated by Django 3.0.7 on 2020-07-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200715_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='solution_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='wihda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wihda'),
        ),
        migrations.AlterField(
            model_name='summary_wihda',
            name='wihda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wihda'),
        ),
    ]
