# Generated by Django 3.0.7 on 2020-07-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200715_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_wihda',
            name='wihda',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.Wihda'),
        ),
    ]
