# Generated by Django 3.0.7 on 2020-07-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200715_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='solution_link',
            field=models.URLField(blank=True, null=True),
        )
    ]
