# Generated by Django 3.0.7 on 2020-07-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200719_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='summary_wihda',
            options={'verbose_name_plural': 'Summary_wihdat'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='order_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Order_name'),
        ),
        migrations.AddField(
            model_name='summary_wihda',
            name='order_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Order_name'),
        ),
    ]
