# Generated by Django 3.0.7 on 2020-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200720_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='short_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='summary_wihda',
            name='short_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
