# Generated by Django 3.0.7 on 2020-10-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200720_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modakira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=15)),
                ('link', models.URLField()),
                ('order_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Order_name')),
                ('wihda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wihda')),
            ],
            options={
                'verbose_name_plural': 'Modakirates',
            },
        ),
    ]
