# Generated by Django 3.0.7 on 2020-10-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tadaroj_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tadaroj',
            name='school',
        ),
    ]
