# Generated by Django 3.0.7 on 2020-10-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201023_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadaroj',
            name='watika',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Watika'),
            preserve_default=False,
        ),
    ]
