# Generated by Django 3.0.7 on 2020-11-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tadaroj_watika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_wihda',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
